name: Build & Deploy Docker Image and GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2. Connexion à Docker Hub
      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Build de l'image Docker
      - name: Build de l'image Docker
        run: docker build -t mon-dockerhub-user/mon-portfolio:latest .

      # 4. Push sur Docker Hub
      - name: Push sur Docker Hub
        run: docker push mon-dockerhub-user/mon-portfolio:latest

      # 5. Installer Node.js et les dépendances
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      # 6. Construire l'application pour GitHub Pages
      - name: Build the app for GitHub Pages
        run: npm run build

      # 7. Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages

