name: Build & Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build de l'image Docker
        run: docker build -t mon-dockerhub-user/mon-portfolio:latest .

      - name: Push sur Docker Hub
        run: docker push mon-dockerhub-user/mon-portfolio:latest

      # Étape pour déployer sur GitHub Pages
      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Utilise le token GitHub pour authentifier le push
          publish_dir: ./dist  # Spécifie le répertoire contenant le build à déployer
          # Si ton build produit des fichiers HTML dans un autre répertoire, modifie ce chemin
