name: Build & Deploy Docker Image and GitHub Pages

on:
  push:
    branches:
      - main  # Le workflow se déclenche sur chaque push vers la branche main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Cloner le dépôt
      - name: Cloner le dépôt
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2. Connexion à Docker Hub
      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Build de l'image Docker
      - name: Build de l'image Docker
        run: docker build -t cyprien23/mon-portfolio:latest .

      # 4. Push de l'image Docker vers Docker Hub
      - name: Push de l'image Docker
        run: docker push cyprien23/mon-portfolio:latest

      # 5. Installer Node.js et les dépendances
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      # 6. Construire l'application pour GitHub Pages
      - name: Build the app for GitHub Pages
        run: npm run build

      # 7. Vérifier le contenu du dossier dist
      - name: Vérifier le contenu du dossier dist
        run: ls -la ./dist

      # 8. Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
