name: Build & Deploy Docker Image and GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      actions: read

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build de l'image Docker
        run: docker build -t cyprien23/mon-portfolio:latest .

      - name: Push de l'image Docker
        run: docker push cyprien23/mon-portfolio:latest

      - name: Installer Node.js et les dépendances
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Build the app for GitHub Pages
        run: npm run build

      - name: Vérifier le contenu du dossier dist
        run: ls -la ./dist

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages


      - name: Exécuter les tests post-déploiement (Cypress)
        run: |
          npx cypress run --headless
